package org.namuai.offline.core.store

import java.io.File

/**
 * On-disk layout of native-contract §3 under `noBackupFilesDir/namu-models`
 * (DL-008). Path components come only from app-generated IDs that are
 * validated here; nothing from a server response or user input is ever used.
 */
class StorageLayout(val root: File) {
    val journalDir = File(root, "journal")
    val stagingDir = File(root, "staging")
    val releasesDir = File(root, "releases")
    val activePointer = File(root, "active.json")
    val activePointerTmp = File(root, "active.json.tmp")
    val pendingMarker = File(root, "pending-activation.json")
    val pendingMarkerTmp = File(root, "pending-activation.json.tmp")

    fun ensureDirectories() {
        root.mkdirs()
        journalDir.mkdirs()
        stagingDir.mkdirs()
        releasesDir.mkdirs()
    }

    fun stagingFile(transferId: String): File {
        require(TRANSFER_ID.matches(transferId)) { "invalid transfer id" }
        return File(stagingDir, "$transferId.part")
    }

    fun releaseDir(artifactId: String): File {
        require(ARTIFACT_ID.matches(artifactId)) { "invalid artifact id" }
        return File(releasesDir, artifactId)
    }

    fun releaseFile(artifactId: String): File = File(releaseDir(artifactId), MODEL_FILE_NAME)

    companion object {
        const val MODEL_FILE_NAME = "model.gguf"
        val ARTIFACT_ID = Regex("[0-9a-f]{64}")

        /** Lower-case UUIDv4 generated by this app. */
        val TRANSFER_ID = Regex("[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}")
    }
}
