// GENERATED by model-release/inspect-header.mjs — do not edit by hand.
// Derived from CohereLabs/tiny-aya-global-GGUF@a602ea7eeec3a4ad6f77a1b8cf6a53512824922b (tiny-aya-global-q4_k_m.gguf) GGUF metadata (INF-003).
export const RUNTIME_FIXTURE = {
  upstreamRevision: "a602ea7eeec3a4ad6f77a1b8cf6a53512824922b",
  architecture: "cohere2",
  chatTemplateSha256: "2147c474f41b522b7296f74692b9f31e45f49a31465960576a9d321339c5915a",
  addBosToken: true,
  bosText: "<BOS_TOKEN>",
  eosText: "<EOS_TOKEN>",
  eotText: null,
  /** Derived from the locked template's assistant turn; see inspect-header.mjs. */
  stopMarkers: ["<|END_RESPONSE|>","<|END_OF_TURN_TOKEN|>"] as readonly string[],
  generationPrefix: "<|START_OF_TURN_TOKEN|><|CHATBOT_TOKEN|><|START_RESPONSE|>",
  /** Every CONTROL-type token of the locked tokenizer; none may reach visible output. */
  controlTokens: [
    "<PAD>",
    "<MASK_TOKEN>",
    "<BOS_TOKEN>",
    "<EOS_TOKEN>",
    "<UNK>",
    "<|START_OF_TURN_TOKEN|>",
    "<|END_OF_TURN_TOKEN|>",
    "<|USER_TOKEN|>",
    "<|CHATBOT_TOKEN|>",
    "<|SYSTEM_TOKEN|>",
    "<|NEW_FILE|>",
    "<|BEGINNING_OF_PREFIX_FIM_TOKEN|>",
    "<|BEGINNING_OF_MIDDLE_FIM_TOKEN|>",
    "<|BEGINNING_OF_SUFFIX_FIM_TOKEN|>",
    "<|END_OF_MIDDLE_FIM_TOKEN|>",
    "<|START_RESPONSE|>",
    "<|END_RESPONSE|>",
    "<|START_ACTION|>",
    "<|END_ACTION|>",
    "<|START_TOOL_RESULT|>",
    "<|END_TOOL_RESULT|>",
    "<|START_THINKING|>",
    "<|END_THINKING|>"
  ] as readonly string[],
} as const;
